# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652bb0ae61c4f48b226fa1f9e06c362e91ee35b4ab97ce952299b26d3b0f1a2410ac8cf32f35555a1bff864b5dfb6f74ec0af841c2a1e4f7aa34fb5ec0a03ce4

test:
  secret_key_base: acb22cb02141b79586516176cf0609d7866791c76020e94e19c493b9e995fe2b2563e9332f1594d70bf1b29bafd86c55a978cd12729f675d7c820cbbe885b228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
